<h1 align="center">Join Submission, Numeric and Dimension Data Sets to Find Dimensional Facts</h1>

### Import Code Libraries

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML
# Set the format for floating point numbers to show no decimal places
pd.set_option('display.float_format', lambda x: '%.0f' % x)
# Set the pandas column width to unlimited
pd.set_option('display.max_colwidth', None)
# Set the notebook width to 100%
display(HTML("<style>.container { width:100% !important; }</style>"))

### Read Submissions, Numeric and Dimensions Data Sets for Feb. 2024 from [Financial Statement and Notes Data Sets](https://www.sec.gov/dera/data/financial-statement-and-notes-data-set)

In [2]:
# Setting low_memory parameter to False to prevent mixed type inference and default_na parameter to False so that empty strings are not parsed as NaN.
submissions = pd.read_csv('data/2024_02_notes/sub.tsv', sep='\t', low_memory=False, keep_default_na=False)
numericFacts = pd.read_csv('data/2024_02_notes/num.tsv', sep='\t', low_memory=False, keep_default_na=False)
dimensions = pd.read_csv('data/2024_02_notes/dim.tsv', sep='\t', low_memory=False, keep_default_na=False)

### Look at the Contents of submissions Data Frame

In [3]:
submissions

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,accepted,prevrpt,detail,instance,nciks,aciks,pubfloatusd,floatdate,floataxis,floatmems
0,0000005272-24-000007,5272,"AMERICAN INTERNATIONAL GROUP, INC.",6331,US,NY,NEW YORK,10020-1304,1271 AVE OF THE AMERICAS,FL 37,...,2024-02-01 16:24:00.0,0,0,aig-20240201_htm.xml,1,,,,,
1,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,2024-02-01 15:48:00.0,0,1,adp-20231231_htm.xml,1,,,,,
2,0000008947-24-000024,8947,AZZ INC,3470,US,TX,FORT WORTH,76107,"ONE MUSEUM PLACE, SUITE 500",3100 W 7TH STREET,...,2024-02-01 16:33:00.0,0,0,azz-20240201_htm.xml,1,,,,,
3,0000009389-24-000003,9389,BALL CORP,3411,US,CO,WESTMINSTER,80021,9200 W. 108TH CIRCLE,,...,2024-02-01 08:17:00.0,1,0,ball-20240201x8k_htm.xml,1,,,,,
4,0000010795-24-000015,10795,BECTON DICKINSON & CO,3841,US,NJ,FRANKLIN LAKES,07417-1880,ONE BECTON DR,,...,2024-02-01 06:33:00.0,0,0,bdx-20240201_htm.xml,1,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9395,0001999371-24-002923,1459862,ABRDN PALLADIUM ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,2024-02-29 15:21:00.0,0,1,pall-10k_123123_htm.xml,1,,227559998.00,20230630,,1
9396,0001999371-24-002926,1460235,ABRDN PLATINUM ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,2024-02-29 15:31:00.0,0,1,pplt-10k_123123_htm.xml,1,,903420022.00,20230630,,1
9397,0001999371-24-002930,1450922,ABRDN SILVER ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,2024-02-29 15:44:00.0,0,1,sivr-10k_123123_htm.xml,1,,1079390000.00,20230630,,1
9398,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,2024-02-29 16:08:00.0,0,1,gltr-10k_123123_htm.xml,1,,989064023.00,20230630,,1
9399,0002003881-24-000006,2003881,"STIRLING HOTELS & RESORTS, INC.",6798,US,TX,DALLAS,75254,14185 DALLAS PARKWAY,SUITE 1200,...,2024-02-29 15:58:00.0,0,0,shr-20240229_htm.xml,1,,,,,

### Look at the Contents of numericFacts Data Frame

In [4]:
numericFacts

,adsh,tag,version,ddate,qtrs,uom,dimh,iprx,value,footnote,footlen,dimn,coreg,durp,datp,dcml
0,0001288847-24-000012,CashAndCashEquivalentsFairValueDisclosure,us-gaap/2023,20231231,0,USD,0xf1a3f7ab0ed5cabeb17982b56e2bd348,0,0.0000,,0,1,,0,0,-3
1,0001558370-24-002208,DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPositionLessThan12Months,us-gaap/2023,20221231,0,USD,0x2ec5bd062194389885092fd6ee4cdf99,0,5138000.0000,,0,1,,0,0,-3
2,0000831259-24-000011,DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet,us-gaap/2023,20231231,0,USD,0x644fcede5f5b4922957054761702c354,0,-1000000.0000,,0,2,,0,0,-6
3,0000950170-24-022519,DebtInstrumentInterestRateStatedPercentage,us-gaap/2023,20221231,0,pure,0x47fd5eced1f31d7f51f9c49075c62a37,0,0.0475,,0,1,,0,0,4
4,0001505155-24-000013,DebtInstrumentCashInterestCostsPercent,0001505155-24-000013,20211231,4,pure,0x00000000,0,0.0540,,0,0,,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5206924,0001437749-24-005407,NumberOfRealEstateProperties,us-gaap/2023,20231231,0,pure,0x4902ad20246fa3955a54e502a3050cd8,0,7.0000,,0,1,,0,0,32767
5206925,0001683168-24-001084,NetCashProvidedByUsedInOperatingActivities,us-gaap/2023,20231231,2,USD,0x00000000,1,-184951.0000,,0,0,,-0,0,0
5206926,0001597033-24-000020,NetCashProvidedByUsedInOperatingActivitiesContinuingOperations,us-gaap/2023,20231231,4,USD,0x00000000,0,56239000.0000,,0,0,,0,0,-3
5206927,0001655888-24-000008,LongTermDebtFairValue,us-gaap/2023,20221231,0,USD,0x3857fa4bfff0ea8e2aeb9a3279087327,0,287777000.0000,,0,3,,0,0,-3
5206928,0001213900-24-011611,InvestmentOwnedAtFairValue,us-gaap/2023,20230930,0,USD,0xdf6ef244721f26c04a839b35c4da3341,0,1920960.0000,,0,3,,0,0,0

### Look at the Contents of dimensions Data Frame

In [5]:
dimensions

,dimhash,segments,segt
0,0xd5512c6d294aee40238efb1a36a733f6,LongTermContractForPurchaseOfElectricPower=DAECPPA;,0
1,0x7dddba118a15f37c1be71048ab5a5c96,BusinessSegments=SouthernCompanyGas;ProductOrService=GasMarketingServices;,0
2,0x338a503b5b214d006a405f47195ea432,BusinessSegments=ProteinSciences;,0
3,0xd82a31aac24e8c29254c4850169e5a12,CreditFacility=RevolvingCreditFacility;DebtInstrument=AssetBasedLendingCreditAgreement;LongtermDebtType=SecuredDebt;Range=Maximum;,0
4,0x1d0ed180f303d44362d9184ee734f486,BusinessAcquisition=BronxThree;Geographical=NY;RealEstateAndAccumulatedDepreciationDescriptionOfProperty=AccumulatedDepreciationAndAmortizationDescription;,0
...,...,...,...
430714,0x61827103e98aa079e090f5797ce80b27,ConversionOfStockByUniqueDescription=StonepeakWarrantAgreementOne;FinancialInstrument=StonepeakWarrant;MeasurementInputType=MeasurementInputRiskFreeInterestRate;ValuationTechnique=ValuationTechniqueOptionPricingModel;,0
430715,0x0bb5ac52e45740a15b7f5250d415fd9d,FiniteLivedIntangibleAssetsByMajorClass=FruitzBrand;Range=Maximum;,0
430716,0x1f6a2b874ff37c019319beba68cd0d63,FinancingReceivableRecordedInvestmentByClassOfFinancingReceivable=RealEstateConstructionFinancingReceivable;LoanRestructuringModification=WeightedAverageMonthsOfTermExtension;,0
430717,0x2102ea32b9375ad369801a2b40850e41,RealEstateAndAccumulatedDepreciationDescriptionOfProperty=AlmedaCrossingHoustonTX;,0
430718,0x93574754470844ddb102b662de0f3e86,AssetAcquisition=CapesizeBulkCarriers;,0

### Merge submissions Data Frame with numericFacts Data Frame Using adsh Column as a Join Key

In [6]:
mergedSubmissionsAndNumericFactsDF = pd.merge(submissions, numericFacts, on='adsh')

### Merge mergedSubmissionsAndNumericFactsDF Data Frame with dimensions Data Frame Using Dimension Hash Column as a Join Key

In [7]:
mergedDF = pd.merge(mergedSubmissionsAndNumericFactsDF, dimensions, left_on='dimh', right_on='dimhash')

### Look at the Contents of mergedDF Data Frame

In [8]:
mergedDF

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,footnote,footlen,dimn,coreg,durp,datp,dcml,dimhash,segments,segt
0,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,,0,1,,0,0,-5,0x8a65a798158d5224d23c1fff5b4e603b,FinancialInstrument=CorporateDebtSecurities;,0
1,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,,0,1,,0,0,-5,0x8a65a798158d5224d23c1fff5b4e603b,FinancialInstrument=CorporateDebtSecurities;,0
2,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,,0,1,,0,0,-5,0x8a65a798158d5224d23c1fff5b4e603b,FinancialInstrument=CorporateDebtSecurities;,0
3,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,,0,1,,0,0,-5,0x8a65a798158d5224d23c1fff5b4e603b,FinancialInstrument=CorporateDebtSecurities;,0
4,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,,0,1,,0,0,-5,0x8a65a798158d5224d23c1fff5b4e603b,FinancialInstrument=CorporateDebtSecurities;,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5206924,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,,0,1,,0,0,-3,0x097c0dc8761b598d5f685f2b422ea0d6,Currency=XAG;,0
5206925,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,,0,1,,0,0,-3,0x097c0dc8761b598d5f685f2b422ea0d6,Currency=XAG;,0
5206926,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,,0,1,,0,0,-3,0x097c0dc8761b598d5f685f2b422ea0d6,Currency=XAG;,0
5206927,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,,0,1,,0,0,-3,0x097c0dc8761b598d5f685f2b422ea0d6,Currency=XAG;,0
5206928,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,,0,1,,0,0,-3,0x097c0dc8761b598d5f685f2b422ea0d6,Currency=XAG;,0

### Filter for Annual Revenues for Delta Airlines using RevenueFromContractWithCustomerExcludingAssessedTax tag

In [9]:
# Using 4 qtrs for annual revenue
filter = (mergedDF.name == 'DELTA AIR LINES, INC.') \
    & (mergedDF.tag == 'RevenueFromContractWithCustomerExcludingAssessedTax') \
    & (mergedDF.ddate == 20231231) \
    & (mergedDF.qtrs == 4) \
    & (mergedDF.iprx == 0)
revenueFactsForDeltaAirlines = mergedDF[filter][['name', 'tag', 'dimn', 'segments', 'ddate', 'qtrs', 'uom', 'value']].sort_values(by= ['dimn', 'segments'])
# Reset the index of revenueFactsForDeltaAirlines data frame
revenueFactsForDeltaAirlines.reset_index(drop=True, inplace=True)

### Look at the Contents of revenueFactsForDeltaAirlines Data Frame. Notice that Dimensions are in segments Column.

In [10]:
# Left align the columns and headers
leftAlignedDF = revenueFactsForDeltaAirlines.style.set_properties(**{'text-align': 'left'})
leftAlignedDF.set_table_styles([dict(selector='th', props=[('text-align', 'left')])])