<h1 align="center">Join Submissions, Numeric and Tags Data Sets to Find Custom Facts</h1>

### Import Code Libraries

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML
# Set the pandas column width to unlimited
pd.set_option('display.max_colwidth', None)
# Set the notebook width to 100%
display(HTML("<style>.container { width:100% !important; }</style>"))

### Read Submissions, Nemeric and Tags Data Sets for Feb. 2024 from [Financial Statement and Notes Data Sets](https://www.sec.gov/dera/data/financial-statement-and-notes-data-set)

In [2]:
# Setting low_memory parameter to False to prevent mixed type inference and default_na parameter to False so that empty strings are not parsed as NaN.
submissions = pd.read_csv('data/2024_02_notes/sub.tsv', sep='\t', low_memory=False, keep_default_na=False)
numericFacts = pd.read_csv('data/2024_02_notes/num.tsv', sep='\t', low_memory=False, keep_default_na=False)
tags = pd.read_csv('data/2024_02_notes/tag.tsv', sep='\t', low_memory=False, keep_default_na=False)

### Look at the Contents of submissions Data Frame

In [3]:
submissions

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,accepted,prevrpt,detail,instance,nciks,aciks,pubfloatusd,floatdate,floataxis,floatmems
0,0000005272-24-000007,5272,"AMERICAN INTERNATIONAL GROUP, INC.",6331,US,NY,NEW YORK,10020-1304,1271 AVE OF THE AMERICAS,FL 37,...,2024-02-01 16:24:00.0,0,0,aig-20240201_htm.xml,1,,,,,
1,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,2024-02-01 15:48:00.0,0,1,adp-20231231_htm.xml,1,,,,,
2,0000008947-24-000024,8947,AZZ INC,3470,US,TX,FORT WORTH,76107,"ONE MUSEUM PLACE, SUITE 500",3100 W 7TH STREET,...,2024-02-01 16:33:00.0,0,0,azz-20240201_htm.xml,1,,,,,
3,0000009389-24-000003,9389,BALL CORP,3411,US,CO,WESTMINSTER,80021,9200 W. 108TH CIRCLE,,...,2024-02-01 08:17:00.0,1,0,ball-20240201x8k_htm.xml,1,,,,,
4,0000010795-24-000015,10795,BECTON DICKINSON & CO,3841,US,NJ,FRANKLIN LAKES,07417-1880,ONE BECTON DR,,...,2024-02-01 06:33:00.0,0,0,bdx-20240201_htm.xml,1,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9395,0001999371-24-002923,1459862,ABRDN PALLADIUM ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,2024-02-29 15:21:00.0,0,1,pall-10k_123123_htm.xml,1,,227559998.00,20230630,,1
9396,0001999371-24-002926,1460235,ABRDN PLATINUM ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,2024-02-29 15:31:00.0,0,1,pplt-10k_123123_htm.xml,1,,903420022.00,20230630,,1
9397,0001999371-24-002930,1450922,ABRDN SILVER ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,2024-02-29 15:44:00.0,0,1,sivr-10k_123123_htm.xml,1,,1079390000.00,20230630,,1
9398,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,2024-02-29 16:08:00.0,0,1,gltr-10k_123123_htm.xml,1,,989064023.00,20230630,,1
9399,0002003881-24-000006,2003881,"STIRLING HOTELS & RESORTS, INC.",6798,US,TX,DALLAS,75254,14185 DALLAS PARKWAY,SUITE 1200,...,2024-02-29 15:58:00.0,0,0,shr-20240229_htm.xml,1,,,,,

### Look at the Contents of numericFacts Data Frame

In [4]:
numericFacts

,adsh,tag,version,ddate,qtrs,uom,dimh,iprx,value,footnote,footlen,dimn,coreg,durp,datp,dcml
0,0001288847-24-000012,CashAndCashEquivalentsFairValueDisclosure,us-gaap/2023,20231231,0,USD,0xf1a3f7ab0ed5cabeb17982b56e2bd348,0,0.0000,,0,1,,0.000000,0.0,-3
1,0001558370-24-002208,DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPositionLessThan12Months,us-gaap/2023,20221231,0,USD,0x2ec5bd062194389885092fd6ee4cdf99,0,5138000.0000,,0,1,,0.000000,0.0,-3
2,0000831259-24-000011,DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet,us-gaap/2023,20231231,0,USD,0x644fcede5f5b4922957054761702c354,0,-1000000.0000,,0,2,,0.000000,0.0,-6
3,0000950170-24-022519,DebtInstrumentInterestRateStatedPercentage,us-gaap/2023,20221231,0,pure,0x47fd5eced1f31d7f51f9c49075c62a37,0,0.0475,,0,1,,0.000000,0.0,4
4,0001505155-24-000013,DebtInstrumentCashInterestCostsPercent,0001505155-24-000013,20211231,4,pure,0x00000000,0,0.0540,,0,0,,0.010959,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5206924,0001437749-24-005407,NumberOfRealEstateProperties,us-gaap/2023,20231231,0,pure,0x4902ad20246fa3955a54e502a3050cd8,0,7.0000,,0,1,,0.000000,0.0,32767
5206925,0001683168-24-001084,NetCashProvidedByUsedInOperatingActivities,us-gaap/2023,20231231,2,USD,0x00000000,1,-184951.0000,,0,0,,-0.005479,0.0,0
5206926,0001597033-24-000020,NetCashProvidedByUsedInOperatingActivitiesContinuingOperations,us-gaap/2023,20231231,4,USD,0x00000000,0,56239000.0000,,0,0,,0.010959,0.0,-3
5206927,0001655888-24-000008,LongTermDebtFairValue,us-gaap/2023,20221231,0,USD,0x3857fa4bfff0ea8e2aeb9a3279087327,0,287777000.0000,,0,3,,0.000000,0.0,-3
5206928,0001213900-24-011611,InvestmentOwnedAtFairValue,us-gaap/2023,20230930,0,USD,0xdf6ef244721f26c04a839b35c4da3341,0,1920960.0000,,0,3,,0.000000,0.0,0

### Look at the Contents of tags Data Frame

In [5]:
tags

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
0,A.5000EuroDenominatedNotesDue2033Member,0000059478-24-000065,1,1,member,,,.5000% Euro Denominated Notes Due 2033 [Member],.5000% Euro Denominated Notes Due 2033
1,A.C.SolucoesParaPiscinasLda.Member,0000945841-24-000021,1,1,member,,,"A.C. Solucoes para Piscinas, Lda. [Member]","A.C. Solucoes para Piscinas, Lda."
2,A.NattermannCie.GmbHMember,0001121404-24-000009,1,1,member,,,A. Nattermann & Cie. GmbH [Member],A. Nattermann & Cie. GmbH [Member]
3,A0.000Notesdue2025Member,0000320193-24-000005,1,1,member,,,0.000% Notes due 2025 [Member],0.000% Notes due 2025 [Member]
4,A0.000Notesdue2025Member,0000320193-24-000006,1,1,member,,,0.000% Notes due 2025 [Member],0.000% Notes due 2025 [Member]
...,...,...,...,...,...,...,...,...,...
534841,ZZ531120,naics/2023,0,1,member,,,531120 Lessors of Nonresidential Buildings (except Miniwarehouses) [Member],Lessors of Nonresidential Buildings (except Mini Warehouses)
534842,ZZ541214,naics/2023,0,1,member,,,541214 Payroll Services [Member],Payroll Services
534843,ZZ721211,naics/2023,0,1,member,,,721211 RV (Recreational Vehicle) Parks and Campgrounds [Member],RV (Recreational Vehicle) Parks and Campgrounds
534844,ZZ811412,naics/2023,0,1,member,,,811412 Appliance Repair and Maintenance [Member],Appliance Repair and Maintenance
534845,ZZ812930,naics/2023,0,1,member,,,812930 Parking Lots and Garages [Member],Parking Lots and Garages

### Filter for Custom Monetary Tags

In [6]:
# use value of abstarct column as 0 to filter for concrete (non-abstract) tags
customTagsDF = tags[(tags.custom == 1) & (tags.abstract == 0) & (tags.datatype == 'monetary')]
customTagsDF

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
474,A1031ExchangeFundsForBusinessCombinations,0000089089-24-000011,1,0,monetary,D,C,1031 Exchange Funds for Business Combinations,1031 Exchange Funds for Business Combinations
1099,A155SeniorNotesDue2026,0000920148-24-000014,1,0,monetary,I,C,1.55% senior notes due 2026,1.55% senior notes due 2026
1445,A2.30SeniorNotesDue2024LongTerm,0000920148-24-000014,1,0,monetary,I,C,2.30% senior notes due 2024 long term,2.30% senior notes due 2024 long term
1446,A2.30SeniorNotesDue2024ShortTerm,0000920148-24-000014,1,0,monetary,I,C,2.30% senior notes due 2024 short term,2.30% senior notes due 2024 short term
1541,A2.95seniornotesdue2029,0000920148-24-000014,1,0,monetary,I,C,2.95% senior notes due 2029,2.95% senior notes due 2029
...,...,...,...,...,...,...,...,...,...
534481,ZeroCouponNotesAggregateCarryingValue,0000019617-24-000225,1,0,monetary,I,C,Zero Coupon Notes Aggregate Carrying Value,"Including current and noncurrent portions, aggregate carrying amount of zero-coupon long-term borrowings as of the balance sheet date. Which had initial maturities beyond one year or beyond the normal operating cycle, if longer, and after deducting unamortized discount or premiums, if any."
534482,ZeroCouponNotesAggregatePrincipalAmountAtMaturity,0000019617-24-000225,1,0,monetary,I,C,Zero-coupon notes - aggregate principal amount at maturity,Includes aggregate principal amount of zero-coupon long-term borrowings at their maturities.
534710,ZimberelimabResearchAndDevelopmentAndCommercialActivities,0001724521-24-000052,1,0,monetary,D,C,Zimberelimab Research and Development and Commercial Activities,Zimberelimab research and development and commercial activities.
534724,ZimVieTermLoanMaximumBorrowingCapacity,0000950170-24-019353,1,0,monetary,I,C,Zim Vie Term Loan Maximum Borrowing Capacity,ZimVie term loan maximum borrowing capacity.
534767,ZolgensmaRoyaltiesPaidToHCR,0000950170-24-021161,1,0,monetary,D,C,Zolgensma Royalties Paid To H C R,Zolgensma royalties paid to HCR.

### Merge submissions Data Frame with numericFacts Data Frame Using adsh Column as a Join Key

In [7]:
mergedSubmissionsAndNumericFactsDF = pd.merge(submissions, numericFacts, on='adsh')

### Merge mergedSubmissionsAndNumericFactsDF Data Frame with customTagsDF Data Frame Using adsh and tag as Join Keys

In [8]:
# Please note that version column = adsh for custom tags
mergedDF = pd.merge(mergedSubmissionsAndNumericFactsDF, customTagsDF, left_on=['adsh', 'tag'], right_on=['version', 'tag'])

### Look at the Contents of mergedDF Data Frame

In [9]:
mergedDF

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,datp,dcml,version_y,custom,abstract,datatype,iord,crdr,tlabel,doc
0,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,0.0,-5,0000008670-24-000007,1,0,monetary,D,C,"Contract With Customer, Liability, Increase (Decrease) From Foreign Currency Translation","Contract With Customer, Liability, Increase (Decrease) From Foreign Currency Translation"
1,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,0.0,-5,0000008670-24-000007,1,0,monetary,I,D,Funds Held Clients,"Represents assets that, based upon the Company's intent, are restricted for use solely for the purposes of satisfying the obligations to remit funds relating to the Companys payroll and payroll tax filing services"
2,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,0.0,-5,0000008670-24-000007,1,0,monetary,I,D,Funds Held Clients,"Represents assets that, based upon the Company's intent, are restricted for use solely for the purposes of satisfying the obligations to remit funds relating to the Companys payroll and payroll tax filing services"
3,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,0.0,-5,0000008670-24-000007,1,0,monetary,I,C,Total current liabilities before client funds obligations,Total current liabilities before client funds obligations
4,0000008670-24-000007,8670,AUTOMATIC DATA PROCESSING INC,7374,US,NJ,ROSELAND,07068,ONE ADP BOULVARD,,...,0.0,-5,0000008670-24-000007,1,0,monetary,I,C,Total current liabilities before client funds obligations,Total current liabilities before client funds obligations
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564166,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,0.0,-3,0001999371-24-002937,1,0,monetary,D,C,Total gain on investment in gold,The net gain or loss in the period on bullion.
564167,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,0.0,-3,0001999371-24-002937,1,0,monetary,D,C,Total gain on investment in gold,The net gain or loss in the period on bullion.
564168,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,0.0,0,0001999371-24-002937,1,0,monetary,D,D,Maximum sponsor fee for legal expenses,Maximum sponsor fee for legal expenses.
564169,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,0.0,0,0001999371-24-002937,1,0,monetary,I,C,Bullion payable,Amount of bullion payable at market value as of the reporting date.
564170,0001999371-24-002937,1483386,ABRDN PRECIOUS METALS BASKET ETF TRUST,6221,US,PA,PHILADELPHIA,19103,C/O ABRDN,"1900 MARKET STREET, SUITE 200",...,0.0,0,0001999371-24-002937,1,0,monetary,I,C,Bullion payable,Amount of bullion payable at market value as of the reporting date.

### Filter for Facts with Custom Tags for AMAZON COM INC

In [10]:
# Using data date (ddate) = 20231231 for year-end facts and dimn = 0 for non-dimensional facts
filter = (mergedDF.name == 'AMAZON COM INC') & (mergedDF.ddate == 20231231) & (mergedDF.dimn == 0)
# Sort values by tag column
customFactsForAmazon = mergedDF[filter][['name', 'tag', 'dimn', 'ddate', 'qtrs', 'uom', 'value']].sort_values(by= 'tag')
customFactsForAmazon.reset_index(drop=True, inplace=True)
customFactsForAmazon

,name,tag,dimn,ddate,qtrs,uom,value
0,AMAZON COM INC,DeferredTaxAssetsOperatingLeaseLiabilities,0,20231231,0,USD,19922000000.0000
1,AMAZON COM INC,DeferredTaxLiabilitiesOperatingLeaseAssets,0,20231231,0,USD,18648000000.0000
2,AMAZON COM INC,FinanceLeaseCost,0,20231231,4,USD,6203000000.0000
3,AMAZON COM INC,FinancingObligationsCurrent,0,20231231,0,USD,271000000.0000
4,AMAZON COM INC,FinancingObligationsFutureMinimumPaymentsDue,0,20231231,0,USD,8641000000.0000
5,AMAZON COM INC,FinancingObligationsFutureMinimumPaymentsDueAfterYearFive,0,20231231,0,USD,6282000000.0000
6,AMAZON COM INC,FinancingObligationsFutureMinimumPaymentsDueInFiveYears,0,20231231,0,USD,484000000.0000
7,AMAZON COM INC,FinancingObligationsFutureMinimumPaymentsDueInFourYears,0,20231231,0,USD,476000000.0000
8,AMAZON COM INC,FinancingObligationsFutureMinimumPaymentsDueInThreeYears,0,20231231,0,USD,468000000.0000
9,AMAZON COM INC,FinancingObligationsFutureMinimumPaymentsDueInTwoYears,0,20231231,0,USD,462000000.0000
10,AMAZON COM INC,FinancingObligationsFutureMinimumPaymentsDueNextTwelveMonths,0,20231231,0,USD,469000000.0000
11,AMAZON COM INC,FinancingObligationsNoncurrent,0,20231231,0,USD,6600000000.0000
12,AMAZON COM INC,ForeignCurrencyTransactionGainLossOnIntercompanyBalances,0,20231231,4,USD,-329000000.0000
13,AMAZON COM INC,FulfillmentExpense,0,20231231,4,USD,90619000000.0000
14,AMAZON COM INC,InterestPaidFinancingObligations,0,20231231,4,USD,196000000.0000
15,AMAZON COM INC,InterestPaidOnLongTermDebt,0,20231231,4,USD,2608000000.0000
16,AMAZON COM INC,LeaseLiability,0,20231231,0,USD,87748000000.0000
17,AMAZON COM INC,LeaseLiabilityCurrent,0,20231231,0,USD,10451000000.0000
18,AMAZON COM INC,LeaseLiabilityNoncurrent,0,20231231,0,USD,77297000000.0000
19,AMAZON COM INC,LeaseLiabilityNoncurrent,0,20231231,0,USD,77297000000.0000
20,AMAZON COM INC,LeaseLiabilityPaymentsDue,0,20231231,0,USD,104883000000.0000
21,AMAZON COM INC,LeaseLiabilityUndiscountedExcessAmount,0,20231231,0,USD,17135000000.0000
22,AMAZON COM INC,LesseeLeaseNotYetCommencedFutureMinimumPaymentsDue,0,20231231,0,USD,38181000000.0000
23,AMAZON COM INC,LesseeLeaseNotYetCommencedFutureMinimumPaymentsDueAfterYearFive,0,20231231,0,USD,24860000000.0000
24,AMAZON COM INC,LesseeLeaseNotYetCommencedFutureMinimumPaymentsDueInFiveYears,0,20231231,0,USD,2979000000.0000
25,AMAZON COM INC,LesseeLeaseNotYetCommencedFutureMinimumPaymentsDueInFourYears,0,20231231,0,USD,2852000000.0000
26,AMAZON COM INC,LesseeLeaseNotYetCommencedFutureMinimumPaymentsDueInThreeYears,0,20231231,0,USD,2836000000.0000
27,AMAZON COM INC,LesseeLeaseNotYetCommencedFutureMinimumPaymentsDueInTwoYears,0,20231231,0,USD,2620000000.0000
28,AMAZON COM INC,LesseeLeaseNotYetCommencedFutureMinimumPaymentsDueNextTwelveMonths,0,20231231,0,USD,2034000000.0000
29,AMAZON COM INC,LongTermDebtIncludingInterest,0,20231231,0,USD,96872000000.0000
30,AMAZON COM INC,LongTermDebtMaturitiesRepaymentsOfPrincipalAndInterestAfterYearFive,0,20231231,0,USD,60176000000.0000
31,AMAZON COM INC,LongTermDebtMaturitiesRepaymentsOfPrincipalAndInterestInNextTwelveMonths,0,20231231,0,USD,10616000000.0000
32,AMAZON COM INC,LongTermDebtMaturitiesRepaymentsOfPrincipalAndInterestInYearFive,0,20231231,0,USD,3643000000.0000
33,AMAZON COM INC,LongTermDebtMaturitiesRepaymentsOfPrincipalAndInterestInYearFour,0,20231231,0,USD,10404000000.0000
34,AMAZON COM INC,LongTermDebtMaturitiesRepaymentsOfPrincipalAndInterestInYearThree,0,20231231,0,USD,4858000000.0000
35,AMAZON COM INC,LongTermDebtMaturitiesRepaymentsOfPrincipalAndInterestInYearTwo,0,20231231,0,USD,7175000000.0000
36,AMAZON COM INC,MiscellaneousIncomeExpense,0,20231231,4,USD,-177000000.0000
37,AMAZON COM INC,NonmarketableSecuritiesAgreedAdditionalInvestmentMaximum,0,20231231,0,USD,2750000000.0000
38,AMAZON COM INC,OtherComprehensiveIncomeOtherTax,0,20231231,4,USD,-1000000.0000
39,AMAZON COM INC,PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther,0,20231231,4,USD,5839000000.0000
40,AMAZON COM INC,PaymentsToAcquireNonmarketableSecurities,0,20231231,4,USD,1250000000.0000
41,AMAZON COM INC,ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives,0,20231231,4,USD,4596000000.0000
42,AMAZON COM INC,PropertyAndEquipmentDerecognizedAfterConstructionPeriodBuildToSuitArrangement,0,20231231,4,USD,1374000000.0000
43,AMAZON COM INC,PropertyAndEquipmentObtainedInExchangeForFinancingObligations,0,20231231,4,USD,357000000.0000
44,AMAZON COM INC,RepaymentsOfLongTermFinancingObligations,0,20231231,4,USD,271000000.0000
45,AMAZON COM INC,TechnologyAndInfrastructureExpense,0,20231231,4,USD,85622000000.0000
46,AMAZON COM INC,VideoandMusicContentCapitalizedCosts,0,20231231,0,USD,17400000000.0000
47,AMAZON COM INC,VideoandMusicContentExpense,0,20231231,4,USD,18900000000.0000